[workspace]
resolver = "2"
members = [
    "compiler/ast", 
    "compiler/errors", 
    "compiler/lexer", 
    "compiler/parser",
    "compiler/prettyprint",
    "compiler/analyzer",
    "compiler/utils",
    "compiler/macros",
    "cli",
    "server",
    "repl",
]
