[workspace]
members = [
    "source/ast", 
    "source/corelib", 
    "source/errors", 
    "source/lexer", 
    "source/parser",
    "source/printer",
    "source/repl",
    "source/analyzer",
    "source/server",
    "source/utils",
    "source/macros"
    ]
