[workspace]
resolver = "2"
members = [
    "source/ast", 
    "source/errors", 
    "source/lexer", 
    "source/parser",
    "source/pretty",
    "source/bytecode",
    "source/repl",
    "source/analyzer",
    "source/server",
    "source/utils",
    "source/macros",
    "source/cli",
    "source/vm"
    ]
