[project.info]
name = "whirlwind-examples.self-host"
type = "binary"
version = "0.0.1"
description = "An experimental compiler for Whirlwind, written in Whirlwind."
authors = ["The Whirlwind Team"]
namespace = "system"
entry = "source/main.wrl"
